# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./

# Use pnpm if available, fallback to npm
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN npm run build

# Expose any port if needed (not necessary for stdio based server)

# Start the MCP server via CLI
ENTRYPOINT ["node", "dist/cli.js"]
